// GENERATED by tools/gen_registry_kotlin.py from rules/rule_registry_v1.0.json — DO NOT EDIT.
// Regenerate after any registry change; CI fails if this file is stale (decision D-030).
@file:Suppress("ObjectPropertyName", "ClassName", "unused", "SpellCheckingInspection")

package com.personalfitnesscoach.engine.registry

object Registry {
    const val VERSION: String = "1.0.1"
    const val SHA256: String = "ed96e4ad0200f46315b15af986b81c5aff59b6d6ca3a16939e46221df122d9ad"
    const val RULE_COUNT: Int = 140

    /** Every rule ID with its confidence label, for the coach's "Why?" detail. */
    val confidence: Map<String, String> = mapOf(
        "SAF-001" to "High Evidence",
        "SAF-002" to "High Evidence",
        "SAF-003" to "Expert Practice",
        "SAF-004" to "Expert Practice",
        "SAF-005" to "Expert Practice",
        "SAF-006" to "Product Rule (not an evidence claim)",
        "SAF-007" to "Expert Practice",
        "SAF-008" to "Product Rule (not an evidence claim)",
        "SAF-009" to "Product Rule (not an evidence claim)",
        "COACH-001" to "Product Rule (not an evidence claim)",
        "PH-001" to "High Evidence",
        "FREQ-001" to "High Evidence",
        "FREQ-002" to "Moderate Evidence",
        "FREQ-003" to "High Evidence",
        "FREQ-004" to "Moderate Evidence",
        "FREQ-005" to "Expert Practice",
        "VOL-001" to "Moderate Evidence",
        "VOL-002" to "Moderate Evidence",
        "VOL-003" to "Expert Practice",
        "VOL-004" to "Expert Practice",
        "VOL-005" to "Limited Evidence",
        "VOL-006" to "Expert Practice",
        "VOL-007" to "Expert Practice",
        "VOL-008" to "Expert Practice",
        "INT-001" to "Moderate Evidence",
        "INT-002" to "Moderate Evidence",
        "INT-003" to "Moderate Evidence",
        "INT-004" to "Moderate Evidence",
        "INT-005" to "Moderate Evidence",
        "INT-006" to "Moderate Evidence",
        "INT-007" to "Expert Practice",
        "REP-001" to "High Evidence",
        "REP-002" to "High Evidence",
        "REP-003" to "Moderate Evidence",
        "REP-004" to "Moderate Evidence",
        "REP-005" to "Expert Practice",
        "REP-006" to "Expert Practice",
        "REST-001" to "Moderate Evidence",
        "REST-002" to "Moderate Evidence",
        "REST-003" to "Moderate Evidence",
        "REST-004" to "Expert Practice",
        "REST-005" to "Expert Practice",
        "REST-006" to "Expert Practice",
        "REST-007" to "Expert Practice",
        "ORD-001" to "Moderate Evidence",
        "ORD-002" to "Expert Practice",
        "ORD-003" to "Expert Practice",
        "CON-001" to "Moderate Evidence",
        "CON-002" to "Limited Evidence",
        "CON-003" to "Expert Practice",
        "CON-004" to "Moderate Evidence",
        "CON-005" to "Moderate Evidence",
        "CON-006" to "Limited Evidence",
        "AER-001" to "Moderate Evidence",
        "AER-002" to "Limited Evidence",
        "AER-003" to "Expert Practice",
        "HIIT-001" to "Expert Practice",
        "HIIT-002" to "Moderate Evidence",
        "HIIT-003" to "Expert Practice",
        "HIIT-004" to "Expert Practice",
        "HIIT-005" to "Expert Practice",
        "MOD-001" to "Product Rule (not an evidence claim)",
        "MOD-002" to "Expert Practice",
        "PAT-001" to "Expert Practice",
        "PAT-002" to "Expert Practice",
        "PAT-003" to "Expert Practice",
        "PAT-004" to "Expert Practice",
        "BW-001" to "Expert Practice",
        "BW-002" to "Expert Practice",
        "CORE-001" to "Expert Practice",
        "CORE-002" to "Expert Practice",
        "CORE-003" to "Expert Practice",
        "MOB-001" to "Moderate Evidence",
        "MOB-002" to "Moderate Evidence",
        "MOB-003" to "Expert Practice",
        "MOB-004" to "Moderate Evidence",
        "MOB-005" to "Expert Practice",
        "WU-001" to "Moderate Evidence",
        "WU-002" to "Expert Practice",
        "WU-003" to "Expert Practice",
        "WU-004" to "Expert Practice",
        "RDY-001" to "Expert Practice",
        "RDY-002" to "Expert Practice",
        "RDY-003" to "Expert Practice",
        "RDY-004" to "Expert Practice",
        "RDY-005" to "Moderate Evidence",
        "RDY-006" to "Expert Practice",
        "RDY-007" to "Product Rule (not an evidence claim)",
        "LOAD-001" to "Moderate Evidence",
        "LOAD-002" to "Moderate Evidence",
        "LOAD-003" to "Moderate Evidence",
        "LOAD-004" to "Limited Evidence",
        "LOAD-005" to "Expert Practice",
        "LOAD-006" to "Expert Practice",
        "DEL-001" to "Expert Practice",
        "DEL-002" to "Expert Practice",
        "DEL-003" to "Limited Evidence",
        "DEL-004" to "Expert Practice",
        "PER-001" to "Moderate Evidence",
        "PER-002" to "Expert Practice",
        "PER-003" to "Expert Practice",
        "PER-004" to "Expert Practice",
        "PER-005" to "Expert Practice",
        "PER-006" to "Product Rule (not an evidence claim)",
        "PROG-001" to "Moderate Evidence",
        "PROG-002" to "Expert Practice",
        "PROG-003" to "Product Rule (not an evidence claim)",
        "PROG-004" to "Expert Practice",
        "PROG-005" to "Expert Practice",
        "PROG-006" to "Expert Practice",
        "PROG-007" to "Expert Practice",
        "PROG-008" to "Expert Practice",
        "REG-001" to "Expert Practice",
        "REG-002" to "Expert Practice",
        "REG-003" to "Expert Practice",
        "REG-004" to "Moderate Evidence",
        "REG-005" to "Expert Practice",
        "CAL-001" to "Expert Practice",
        "SUB-001" to "Product Rule (not an evidence claim)",
        "SUB-002" to "Expert Practice",
        "SUB-003" to "Product Rule (not an evidence claim)",
        "TIME-001" to "Expert Practice",
        "TIME-002" to "Expert Practice",
        "TIME-003" to "Expert Practice",
        "TIME-004" to "Product Rule (not an evidence claim)",
        "GEN-001" to "Product Rule (not an evidence claim)",
        "SCH-001" to "Expert Practice",
        "SCH-002" to "Expert Practice",
        "SCH-003" to "Product Rule (not an evidence claim)",
        "EXP-001" to "Expert Practice",
        "EXP-002" to "Expert Practice",
        "AGE-001" to "High Evidence",
        "IND-001" to "Moderate Evidence",
        "EQ-001" to "Moderate Evidence",
        "EQ-002" to "Product Rule (not an evidence claim)",
        "ADH-001" to "Expert Practice",
        "ADH-002" to "Moderate Evidence",
        "ADH-003" to "Expert Practice",
        "ADH-004" to "Moderate Evidence",
        "DATA-001" to "Product Rule (not an evidence claim)",
    )

    val titles: Map<String, String> = mapOf(
        "SAF-001" to "Pre-participation screening and conservative mode",
        "SAF-002" to "Red-flag symptoms trigger SAFETY STOP",
        "SAF-003" to "In-session pain protocol",
        "SAF-004" to "Persistent pain and region conservative mode",
        "SAF-005" to "Hard workload caps",
        "SAF-006" to "User additions: warn, confirm, absolute ceiling",
        "SAF-007" to "Illness gate",
        "SAF-008" to "Final pre-render safety validator",
        "SAF-009" to "AI coach boundary",
        "COACH-001" to "Coaching voice",
        "PH-001" to "WHO floor accounting",
        "FREQ-001" to "Training days per week",
        "FREQ-002" to "Per-muscle exposures",
        "FREQ-003" to "Resistance training days",
        "FREQ-004" to "Main-pattern frequency in strength blocks",
        "FREQ-005" to "Aerobic exposure distribution",
        "VOL-001" to "Hard set definition",
        "VOL-002" to "Fractional set counting",
        "VOL-003" to "Volume landmarks (fractional sets/muscle/week)",
        "VOL-004" to "Fatigue-driven volume reduction",
        "VOL-005" to "Per-session per-muscle cap",
        "VOL-006" to "Weekly volume progression within a block",
        "VOL-007" to "Systemic stress units (planning)",
        "VOL-008" to "Working sets per session cap",
        "INT-001" to "RPE-RIR mapping validity",
        "INT-002" to "RIR targets",
        "INT-003" to "Failure policy",
        "INT-004" to "Estimated 1RM (Epley, RIR-adjusted)",
        "INT-005" to "Load selection from e1RM",
        "INT-006" to "Teaching effort to beginners",
        "INT-007" to "In-session autoregulation",
        "REP-001" to "Strength range",
        "REP-002" to "Hypertrophy range",
        "REP-003" to "Muscular endurance range",
        "REP-004" to "Power",
        "REP-005" to "Core dosing",
        "REP-006" to "Conditioning units",
        "REST-001" to "Heavy compounds",
        "REST-002" to "Moderate compounds",
        "REST-003" to "Isolation / accessories",
        "REST-004" to "Non-competing supersets",
        "REST-005" to "Circuits",
        "REST-006" to "Core",
        "REST-007" to "Autoregulated rest and compression",
        "ORD-001" to "Session sequence",
        "ORD-002" to "Order exceptions",
        "ORD-003" to "Superset eligibility",
        "CON-001" to "Strength first in shared sessions",
        "CON-002" to "Same-day separation",
        "CON-003" to "HIIT vs heavy legs",
        "CON-004" to "Low-impact modality preference",
        "CON-005" to "Power protection",
        "CON-006" to "Aerobic dose in strength blocks",
        "AER-001" to "Aerobic intensity zones",
        "AER-002" to "Weekly intensity distribution",
        "AER-003" to "Aerobic progression",
        "HIIT-001" to "Weekly HIIT ceiling",
        "HIIT-002" to "HIIT protocol menu",
        "HIIT-003" to "HIIT prerequisites",
        "HIIT-004" to "HIIT spacing",
        "HIIT-005" to "Per-session HIIT work caps",
        "MOD-001" to "Excluded modalities",
        "MOD-002" to "Modality matrix and selection score",
        "PAT-001" to "Weekly pattern coverage",
        "PAT-002" to "Pull:push ratio",
        "PAT-003" to "Knee:hip ratio",
        "PAT-004" to "Unilateral minimum",
        "BW-001" to "Bodyweight progression levers",
        "BW-002" to "Bodyweight step-up trigger",
        "CORE-001" to "Anti-movement emphasis",
        "CORE-002" to "Core progression",
        "CORE-003" to "Core frequency and volume",
        "MOB-001" to "Pre-workout dynamic mobility",
        "MOB-002" to "Static stretching timing",
        "MOB-003" to "Intra-workout mobility",
        "MOB-004" to "Full range of motion default",
        "MOB-005" to "Off-day routine",
        "WU-001" to "RAMP warm-up",
        "WU-002" to "Ramp-up sets",
        "WU-003" to "Warm-up compression",
        "WU-004" to "Age-adjusted warm-up",
        "RDY-001" to "Readiness raw score",
        "RDY-002" to "Personal baseline blend",
        "RDY-003" to "Readiness tiers",
        "RDY-004" to "Tier modifications",
        "RDY-005" to "Sleep-hours caps",
        "RDY-006" to "Fatigue-signal step-down",
        "RDY-007" to "User tier choice",
        "LOAD-001" to "Session load",
        "LOAD-002" to "sRPE collection timing",
        "LOAD-003" to "Weekly load, monotony, strain",
        "LOAD-004" to "EWMA acute:chronic ratio (soft flag)",
        "LOAD-005" to "Planned weekly load cap",
        "LOAD-006" to "Cold start",
        "DEL-001" to "Fatigue signals",
        "DEL-002" to "Deload decision",
        "DEL-003" to "Deload prescription",
        "DEL-004" to "Resumption after deload",
        "PER-001" to "Autoregulated hybrid architecture",
        "PER-002" to "Block length",
        "PER-003" to "12-month block sequence",
        "PER-004" to "Non-maximal check-ins",
        "PER-005" to "Disruption handling",
        "PER-006" to "Priority weighting",
        "PROG-001" to "Load progression",
        "PROG-002" to "Double progression",
        "PROG-003" to "Rounding to real equipment",
        "PROG-004" to "Hold or reduce",
        "PROG-005" to "Bodyweight progression",
        "PROG-006" to "Conditioning progression",
        "PROG-007" to "Progression caps",
        "PROG-008" to "Technique gate",
        "REG-001" to "Failed targets",
        "REG-002" to "1-2 missed sessions",
        "REG-003" to "3 missed sessions or 7-13 days off",
        "REG-004" to "Layoff >= 14 days",
        "REG-005" to "Return after illness",
        "CAL-001" to "Initial load calibration",
        "SUB-001" to "Substitution hard filters",
        "SUB-002" to "Substitution score",
        "SUB-003" to "Preference learning bounds",
        "TIME-001" to "Priority tiers",
        "TIME-002" to "Compression order",
        "TIME-003" to "Extended sessions",
        "TIME-004" to "Time model",
        "GEN-001" to "Workout generation pipeline",
        "SCH-001" to "Weekly templates",
        "SCH-002" to "Spacing",
        "SCH-003" to "Rescheduling",
        "EXP-001" to "Onboarding classification",
        "EXP-002" to "Level promotion",
        "AGE-001" to "Age adjustments",
        "IND-001" to "Sex and prior injury",
        "EQ-001" to "Equipment matrix",
        "EQ-002" to "Crowded-gym constraints",
        "ADH-001" to "Forgiving weekly streak",
        "ADH-002" to "Micro-achievements",
        "ADH-003" to "Stable core, rotating edges",
        "ADH-004" to "Time-efficient option",
        "DATA-001" to "Data taxonomy",
    )
}

/** Rule identifiers; use these instead of string literals. */
object RuleIds {
    const val SAF_001: String = "SAF-001"
    const val SAF_002: String = "SAF-002"
    const val SAF_003: String = "SAF-003"
    const val SAF_004: String = "SAF-004"
    const val SAF_005: String = "SAF-005"
    const val SAF_006: String = "SAF-006"
    const val SAF_007: String = "SAF-007"
    const val SAF_008: String = "SAF-008"
    const val SAF_009: String = "SAF-009"
    const val COACH_001: String = "COACH-001"
    const val PH_001: String = "PH-001"
    const val FREQ_001: String = "FREQ-001"
    const val FREQ_002: String = "FREQ-002"
    const val FREQ_003: String = "FREQ-003"
    const val FREQ_004: String = "FREQ-004"
    const val FREQ_005: String = "FREQ-005"
    const val VOL_001: String = "VOL-001"
    const val VOL_002: String = "VOL-002"
    const val VOL_003: String = "VOL-003"
    const val VOL_004: String = "VOL-004"
    const val VOL_005: String = "VOL-005"
    const val VOL_006: String = "VOL-006"
    const val VOL_007: String = "VOL-007"
    const val VOL_008: String = "VOL-008"
    const val INT_001: String = "INT-001"
    const val INT_002: String = "INT-002"
    const val INT_003: String = "INT-003"
    const val INT_004: String = "INT-004"
    const val INT_005: String = "INT-005"
    const val INT_006: String = "INT-006"
    const val INT_007: String = "INT-007"
    const val REP_001: String = "REP-001"
    const val REP_002: String = "REP-002"
    const val REP_003: String = "REP-003"
    const val REP_004: String = "REP-004"
    const val REP_005: String = "REP-005"
    const val REP_006: String = "REP-006"
    const val REST_001: String = "REST-001"
    const val REST_002: String = "REST-002"
    const val REST_003: String = "REST-003"
    const val REST_004: String = "REST-004"
    const val REST_005: String = "REST-005"
    const val REST_006: String = "REST-006"
    const val REST_007: String = "REST-007"
    const val ORD_001: String = "ORD-001"
    const val ORD_002: String = "ORD-002"
    const val ORD_003: String = "ORD-003"
    const val CON_001: String = "CON-001"
    const val CON_002: String = "CON-002"
    const val CON_003: String = "CON-003"
    const val CON_004: String = "CON-004"
    const val CON_005: String = "CON-005"
    const val CON_006: String = "CON-006"
    const val AER_001: String = "AER-001"
    const val AER_002: String = "AER-002"
    const val AER_003: String = "AER-003"
    const val HIIT_001: String = "HIIT-001"
    const val HIIT_002: String = "HIIT-002"
    const val HIIT_003: String = "HIIT-003"
    const val HIIT_004: String = "HIIT-004"
    const val HIIT_005: String = "HIIT-005"
    const val MOD_001: String = "MOD-001"
    const val MOD_002: String = "MOD-002"
    const val PAT_001: String = "PAT-001"
    const val PAT_002: String = "PAT-002"
    const val PAT_003: String = "PAT-003"
    const val PAT_004: String = "PAT-004"
    const val BW_001: String = "BW-001"
    const val BW_002: String = "BW-002"
    const val CORE_001: String = "CORE-001"
    const val CORE_002: String = "CORE-002"
    const val CORE_003: String = "CORE-003"
    const val MOB_001: String = "MOB-001"
    const val MOB_002: String = "MOB-002"
    const val MOB_003: String = "MOB-003"
    const val MOB_004: String = "MOB-004"
    const val MOB_005: String = "MOB-005"
    const val WU_001: String = "WU-001"
    const val WU_002: String = "WU-002"
    const val WU_003: String = "WU-003"
    const val WU_004: String = "WU-004"
    const val RDY_001: String = "RDY-001"
    const val RDY_002: String = "RDY-002"
    const val RDY_003: String = "RDY-003"
    const val RDY_004: String = "RDY-004"
    const val RDY_005: String = "RDY-005"
    const val RDY_006: String = "RDY-006"
    const val RDY_007: String = "RDY-007"
    const val LOAD_001: String = "LOAD-001"
    const val LOAD_002: String = "LOAD-002"
    const val LOAD_003: String = "LOAD-003"
    const val LOAD_004: String = "LOAD-004"
    const val LOAD_005: String = "LOAD-005"
    const val LOAD_006: String = "LOAD-006"
    const val DEL_001: String = "DEL-001"
    const val DEL_002: String = "DEL-002"
    const val DEL_003: String = "DEL-003"
    const val DEL_004: String = "DEL-004"
    const val PER_001: String = "PER-001"
    const val PER_002: String = "PER-002"
    const val PER_003: String = "PER-003"
    const val PER_004: String = "PER-004"
    const val PER_005: String = "PER-005"
    const val PER_006: String = "PER-006"
    const val PROG_001: String = "PROG-001"
    const val PROG_002: String = "PROG-002"
    const val PROG_003: String = "PROG-003"
    const val PROG_004: String = "PROG-004"
    const val PROG_005: String = "PROG-005"
    const val PROG_006: String = "PROG-006"
    const val PROG_007: String = "PROG-007"
    const val PROG_008: String = "PROG-008"
    const val REG_001: String = "REG-001"
    const val REG_002: String = "REG-002"
    const val REG_003: String = "REG-003"
    const val REG_004: String = "REG-004"
    const val REG_005: String = "REG-005"
    const val CAL_001: String = "CAL-001"
    const val SUB_001: String = "SUB-001"
    const val SUB_002: String = "SUB-002"
    const val SUB_003: String = "SUB-003"
    const val TIME_001: String = "TIME-001"
    const val TIME_002: String = "TIME-002"
    const val TIME_003: String = "TIME-003"
    const val TIME_004: String = "TIME-004"
    const val GEN_001: String = "GEN-001"
    const val SCH_001: String = "SCH-001"
    const val SCH_002: String = "SCH-002"
    const val SCH_003: String = "SCH-003"
    const val EXP_001: String = "EXP-001"
    const val EXP_002: String = "EXP-002"
    const val AGE_001: String = "AGE-001"
    const val IND_001: String = "IND-001"
    const val EQ_001: String = "EQ-001"
    const val EQ_002: String = "EQ-002"
    const val ADH_001: String = "ADH-001"
    const val ADH_002: String = "ADH-002"
    const val ADH_003: String = "ADH-003"
    const val ADH_004: String = "ADH-004"
    const val DATA_001: String = "DATA-001"
}

/** Typed parameters, one object per rule. */
object P {
    object SAF_001 {
        const val questions: Int = 8
        const val rescreen_months: Int = 12
        object conservative_mode {
            const val hiit_allowed: Boolean = false
            const val zone3_allowed: Boolean = false
            const val min_rir: Int = 3
            const val failure_allowed: Boolean = false
        }
        object logic {
            const val symptoms_q3_q4: String = "clearance+conservative"
            const val disease_q1_q2_and_inactive: String = "clearance+conservative"
            const val disease_q1_q2_and_active_no_symptoms: String = "moderate_only_until_clearance"
            const val limit_or_pregnancy_q5: String = "clinician_guidance+conservative"
            const val msk_or_medication_q6_q7: String = "limitation_tags+note"
            const val all_no: String = "standard"
        }
    }
    object SAF_002 {
        val symptoms: List<String> = listOf("chest_pain_pressure_tightness", "fainting_or_near_fainting", "dizziness_lightheadedness", "unusual_breathlessness", "palpitations_irregular_heartbeat", "sudden_severe_pain", "sudden_severe_headache", "one_sided_weakness_numbness", "confusion_or_speech_trouble")
        const val emergency_number_default: String = "112"
        const val first_session_after: String = "LIGHT"
        const val convert_to_lighter_workout: Boolean = false
    }
    object SAF_003 {
        const val continue_max_rating: Int = 3
        val continue_load_reduction_pct: List<Int> = listOf(10, 20)
        const val stop_exercise_min_rating: Int = 4
        const val stop_region_min_rating: Int = 7
        const val substitute_max_joint_stress: Int = 1
        val stop_region_descriptors: List<String> = listOf("sharp", "stabbing", "swelling", "instability", "locking", "numbness", "tingling", "after_fall_or_impact")
    }
    object SAF_004 {
        const val sessions_threshold: Int = 2
        const val days_threshold: Int = 7
        const val region_max_joint_stress: Int = 1
        const val region_min_rir: Int = 3
        const val pain_free_sessions_to_exit: Int = 2
        const val stress_step_up_per_week: Int = 1
    }
    object SAF_005 {
        object fractional_sets_per_muscle_week {
            const val beginner: Int = 12
            const val intermediate: Int = 16
            const val advanced: Int = 20
        }
        object direct_sets_per_muscle_session {
            const val beginner: Int = 6
            const val intermediate: Int = 8
            const val advanced: Int = 10
        }
        object working_sets_per_session {
            const val beginner: Int = 20
            const val intermediate: Int = 25
            const val advanced: Int = 30
        }
        object weekly_ssu {
            const val beginner: Int = 100
            const val intermediate: Int = 140
            const val advanced: Int = 180
        }
        object hiit_sessions_per_week {
            const val default: Int = 2
            const val conditional_max: Int = 3
        }
        object rir0_exercises_per_session {
            const val beginner_first_8_weeks: Int = 0
            const val otherwise: Int = 2
        }
        const val training_days_per_week: Int = 6
        object planned_weekly_load_increase {
            const val early_week_over_week_pct: Int = 20
            const val after_4_weeks_multiplier_of_3wk_mean: Double = 1.2
        }
        object intensity_rise_per_lift_per_week_pct {
            const val beginner: Double = 7.5
            const val intermediate: Int = 5
            const val advanced: Int = 5
        }
    }
    object SAF_006 {
        const val confirm_beyond_cap: Boolean = true
        object absolute_ceiling {
            const val weekly_per_muscle_multiplier_of_cap: Double = 1.5
            const val working_sets_per_session: Int = 40
            const val hiit_sessions_per_week: Int = 4
        }
        const val block_painful_region: Boolean = true
    }
    object SAF_007 {
        val systemic_symptoms: List<String> = listOf("fever", "chills", "body_aches", "chest_symptoms", "vomiting", "diarrhoea")
        const val tier: String = "RECOVERY"
    }
    object SAF_008 {
        val checks: List<String> = listOf("SAF-005", "VOL-005", "VOL-008", "HIIT-001", "HIIT-004", "PAT-001", "PAT-002", "PAT-003", "SAF-003", "SAF-004", "RDY-004", "SAF-001", "INT-003", "LOAD-005", "MOD-001")
        const val fallback: String = "LIGHT_template"
        const val display_unvalidated: Boolean = false
    }
    object SAF_009 {
        const val tier1_required: Boolean = true
        const val tier2_optional: Boolean = true
        const val can_write_parameters: Boolean = false
        val allowed_requests: List<String> = listOf("shorter_session", "substitution", "easier_tier", "explain")
        const val prompt_injection: String = "treat_as_data"
    }
    object COACH_001 {
        val prohibited: List<String> = listOf("body_shaming", "guilt", "punishment_exercise", "extreme_motivation", "medical_claims")
    }
    object PH_001 {
        const val target_equivalent_minutes: Int = 150
        const val upper_range_minutes: Int = 300
        const val vigorous_multiplier: Int = 2
        const val strength_days_min: Int = 2
    }
    object FREQ_001 {
        const val min_days: Int = 2
        const val max_days: Int = 6
        const val min_rest_days: Int = 1
        const val default_days: Int = 3
    }
    object FREQ_002 {
        const val min_exposures_per_week: Int = 2
        const val exposure_min_fractional_sets: Int = 2
    }
    object FREQ_003 {
        const val min_days: Int = 2
    }
    object FREQ_004 {
        const val min: Int = 2
        const val max: Int = 3
        val patterns: List<String> = listOf("squat", "hinge", "horizontal_push", "horizontal_pull")
    }
    object FREQ_005 {
        const val min_days: Int = 3
        const val applies_when_training_days_gte: Int = 3
        const val min_block_minutes: Int = 10
    }
    object VOL_001 {
        const val max_rir: Int = 4
        const val min_rpe: Int = 6
    }
    object VOL_002 {
        const val primary: Double = 1.0
        const val secondary: Double = 0.5
        const val stabiliser: Double = 0.0
    }
    object VOL_003 {
        object maintenance {
            const val beginner: Int = 4
            const val intermediate: Int = 4
            const val advanced: Int = 6
        }
        object block_start {
            const val beginner: Int = 6
            const val intermediate: Int = 8
            const val advanced: Int = 10
        }
        object working_range {
            val beginner: List<Int> = listOf(8, 12)
            val intermediate: List<Int> = listOf(10, 16)
            val advanced: List<Int> = listOf(12, 20)
        }
        object cap {
            const val beginner: Int = 12
            const val intermediate: Int = 16
            const val advanced: Int = 20
        }
    }
    object VOL_004 {
        const val min_signals: Int = 2
        const val min_sessions: Int = 2
        const val accessory_reduction_pct: Int = 30
    }
    object VOL_005 {
        object cap {
            const val beginner: Int = 6
            const val intermediate: Int = 8
            const val advanced: Int = 10
        }
    }
    object VOL_006 {
        object step {
            val beginner: List<Int> = listOf(1, 1)
            val intermediate: List<Int> = listOf(1, 2)
            val advanced: List<Int> = listOf(1, 2)
        }
    }
    object VOL_007 {
        object C {
            const val isolation_or_core: Double = 0.5
            const val machine_or_cable_compound: Double = 0.8
            const val free_weight_compound_carry_sled: Double = 1.0
            const val heavy_bilateral_squat_hinge_ge80pct: Double = 1.5
        }
        object E {
            const val rir0: Double = 1.2
            const val rir1_2: Double = 1.0
            const val rir3_4: Double = 0.8
        }
        object Z_per_min {
            const val Z1: Double = 0.4
            const val Z2: Double = 0.8
            const val Z3_work: Double = 1.5
            const val interval_rest: Double = 0.2
        }
        object J {
            const val rower_skierg_elliptical: Double = 0.9
            const val ropes_kettlebell_sled_carries: Double = 1.0
            const val jump_rope_jumping_circuits: Double = 1.1
        }
        object weekly_ceiling {
            const val beginner: Int = 100
            const val intermediate: Int = 140
            const val advanced: Int = 180
        }
        const val rolling_multiplier: Double = 1.15
        const val k_after_weeks: Int = 4
    }
    object VOL_008 {
        object cap {
            const val beginner: Int = 20
            const val intermediate: Int = 25
            const val advanced: Int = 30
        }
    }
    object INT_001 {
        const val valid_rpe_min: Int = 6
        const val valid_rpe_max: Int = 10
        object mapping {
            const val _10: Int = 0
            const val _9_5: Int = 0
            const val _9: Int = 1
            const val _8_5: Double = 1.5
            const val _8: Int = 2
            const val _7: Int = 3
            const val _6: Int = 4
        }
    }
    object INT_002 {
        object beginner_first_8_weeks {
            const val compound: Int = 3
            const val isolation: Int = 2
        }
        object intermediate {
            val compound: List<Int> = listOf(1, 3)
            val isolation: List<Int> = listOf(0, 2)
        }
        object advanced {
            val compound: List<Int> = listOf(1, 2)
            val isolation: List<Int> = listOf(0, 1)
        }
        const val block_week1_offset: Int = 1
        const val block_last_week_offset: Int = -1
        const val deload_or_light_min_rir: Int = 3
    }
    object INT_003 {
        const val max_exercises_per_session: Int = 2
        val allowed_tiers: List<String> = listOf("FULL")
        const val beginner_lockout_weeks: Int = 8
        val failure_unsafe_examples: List<String> = listOf("barbell_back_squat", "barbell_bench_press", "overhead_press", "deadlift", "loaded_carries", "olympic_lifts")
    }
    object INT_004 {
        const val formula: String = "epley_rir_adjusted"
        const val divisor: Int = 30
        const val max_reps_plus_rir: Int = 12
        const val max_rir: Int = 3
        const val smoothing_alpha: Double = 0.4
        const val max_single_rise_pct: Int = 5
    }
    object INT_005 {
        const val divisor: Int = 30
    }
    object INT_006 {
        const val weeks: Int = 4
        val rir_options: List<String> = listOf("0", "1", "2", "3", "4+")
    }
    object INT_007 {
        const val easy_threshold: Int = -1
        const val hard_threshold: Int = 1
        const val step_up_max_pct: Int = 5
        const val step_down_pct: Int = 5
        const val net_limit_pct: Int = 10
    }
    object REP_001 {
        val reps: List<Int> = listOf(3, 6)
        val pct_1rm: List<Int> = listOf(80, 88)
        val advanced_low_reps: List<Int> = listOf(1, 3)
        const val advanced_low_rep_max_rpe: Int = 8
    }
    object REP_002 {
        val compound: List<Int> = listOf(6, 12)
        val isolation: List<Int> = listOf(8, 20)
        val pct_1rm: List<Int> = listOf(60, 80)
    }
    object REP_003 {
        val reps: List<Int> = listOf(15, 30)
        val seconds: List<Int> = listOf(30, 60)
        const val pct_1rm_max: Int = 60
    }
    object REP_004 {
        val reps: List<Int> = listOf(3, 5)
        val pct_1rm: List<Int> = listOf(30, 70)
        const val max_total_reps: Int = 23
        const val stop_rule: String = "visible_speed_drop"
    }
    object REP_005 {
        val hold_seconds: List<Int> = listOf(10, 45)
        val reps_per_side: List<Int> = listOf(6, 12)
    }
    object REP_006 {
        val units: List<String> = listOf("minutes", "metres", "watts", "calories", "reps")
    }
    object REST_001 {
        const val min_s: Int = 120
        const val max_s: Int = 300
        const val default_s: Int = 180
    }
    object REST_002 {
        const val min_s: Int = 90
        const val max_s: Int = 150
        const val default_s: Int = 120
    }
    object REST_003 {
        const val min_s: Int = 60
        const val max_s: Int = 90
        const val default_s: Int = 75
    }
    object REST_004 {
        const val min_s: Int = 45
        const val max_s: Int = 75
        const val default_s: Int = 60
    }
    object REST_005 {
        const val min_s: Int = 15
        const val max_s: Int = 45
        const val default_s: Int = 30
    }
    object REST_006 {
        const val min_s: Int = 30
        const val max_s: Int = 60
        const val default_s: Int = 45
    }
    object REST_007 {
        val compression_order: List<String> = listOf("P5", "P4", "P3", "P1")
    }
    object ORD_001 {
        val sequence: List<String> = listOf("warmup", "power", "primary_compound", "secondary_compound", "accessories", "core", "conditioning", "cooldown")
    }
    object ORD_002 {
        const val conditioning_priority_lower_volume_reduction_pct: Int = 30
    }
    object ORD_003 {
        val allowed_pairs: List<String> = listOf("push+pull", "upper+lower", "compound+core")
        const val forbid_main_lift_rir_lte: Int = 2
    }
    object CON_001 {
    }
    object CON_002 {
        const val min_hours: Int = 6
        const val hard_aerobic_min_minutes: Int = 30
    }
    object CON_003 {
        const val hours_before_heavy_lower: Int = 24
    }
    object CON_004 {
        const val impact_sessions_per_week_max: Int = 1
    }
    object CON_005 {
    }
    object CON_006 {
        const val max_prescribed_minutes: Int = 150
    }
    object AER_001 {
        object Z1 {
            val cr10: List<Int> = listOf(3, 4)
            val hrr_pct: List<Int> = listOf(40, 59)
            const val who: String = "moderate"
        }
        object Z2 {
            val cr10: List<Int> = listOf(5, 6)
            val hrr_pct: List<Int> = listOf(60, 79)
            const val who: String = "vigorous"
        }
        object Z3 {
            val cr10: List<Int> = listOf(7, 9)
            val hrr_pct: List<Int> = listOf(80, 100)
            const val who: String = "vigorous"
        }
        object Z4 {
            val cr10: List<Int> = listOf(10, 10)
            const val who: String = "vigorous"
        }
    }
    object AER_002 {
        val z1_share: List<Double> = listOf(0.75, 0.8)
    }
    object AER_003 {
        val per_session_minutes: List<Int> = listOf(2, 5)
        const val weekly_increase_pct_max: Int = 15
        val z1_target_minutes: List<Int> = listOf(30, 40)
    }
    object HIIT_001 {
        const val default_max: Int = 2
        const val conditional_max: Int = 3
        const val count_if_z3_work_minutes_gte: Int = 6
        const val count_if_circuit_cr10_gte: Int = 7
        const val circuit_minutes_gte: Int = 8
    }
    object HIIT_002 {
        object long {
            val reps: List<Int> = listOf(3, 5)
            val work_s: List<Int> = listOf(180, 240)
            val rest_s: List<Int> = listOf(120, 180)
            val cr10: List<Int> = listOf(7, 8)
        }
        object medium {
            val reps: List<Int> = listOf(6, 10)
            val work_s: List<Int> = listOf(60, 120)
            val rest_s: List<Int> = listOf(60, 120)
            val cr10: List<Int> = listOf(8, 8)
        }
        object short {
            val reps: List<Int> = listOf(10, 20)
            val work_s: List<Int> = listOf(15, 30)
            val rest_s: List<Int> = listOf(15, 60)
            val cr10: List<Int> = listOf(8, 9)
            const val beginner_ratio: String = "1:2"
        }
        object sprint {
            val reps: List<Int> = listOf(4, 8)
            val work_s: List<Int> = listOf(10, 20)
            val rest_s: List<Int> = listOf(90, 180)
            val cr10: List<Int> = listOf(10, 10)
            const val min_ratio: String = "1:6"
            const val eligibility: String = "advanced"
            const val per_week_max: Int = 1
        }
        object tempo_not_hiit {
            val reps: List<Int> = listOf(2, 3)
            val work_s: List<Int> = listOf(480, 720)
            val rest_s: List<Int> = listOf(120, 180)
            val cr10: List<Int> = listOf(5, 6)
        }
    }
    object HIIT_003 {
        const val base_weeks: Int = 3
        const val first_protocol: String = "short_1_2"
    }
    object HIIT_004 {
        const val preferred_hours: Int = 48
        const val min_hours: Int = 24
    }
    object HIIT_005 {
        const val long_work_min_max: Int = 20
        const val short_work_min_max: Int = 10
        const val sprint_work_min_max: Double = 2.5
        const val post_strength_conditioning_min_max: Int = 35
    }
    object MOD_001 {
        val excluded: List<String> = listOf("treadmill_running", "stationary_bike", "stair_machine")
        val excluded_pending_confirmation: List<String> = listOf("air_fan_bike", "treadmill_walking")
    }
    object MOD_002 {
        object weights {
            const val stimulus_fit: Double = 0.35
            const val interference: Double = 0.25
            const val impact: Double = 0.2
            const val variety: Double = 0.1
            const val preference: Double = 0.1
        }
        object matrix {
            val rower: List<Int> = listOf(5, 3, 1, 3, 2, 2, 5, 5, 5)
            val skierg: List<Int> = listOf(4, 3, 1, 2, 2, 1, 4, 5, 5)
            val elliptical: List<Int> = listOf(4, 2, 1, 1, 1, 1, 5, 3, 3)
            val sled: List<Int> = listOf(4, 4, 1, 1, 2, 3, 2, 5, 3)
            val battle_ropes: List<Int> = listOf(3, 4, 1, 2, 2, 1, 1, 5, 2)
            val kettlebell: List<Int> = listOf(4, 3, 2, 3, 3, 3, 2, 5, 3)
            val carries: List<Int> = listOf(3, 3, 1, 1, 2, 2, 2, 4, 4)
            val medball: List<Int> = listOf(3, 2, 2, 2, 2, 1, 1, 4, 2)
            val bodyweight_circuit: List<Int> = listOf(3, 3, 2, 1, 2, 2, 2, 4, 3)
            val jump_rope: List<Int> = listOf(4, 2, 3, 3, 2, 2, 3, 4, 2)
        }
        val matrix_columns: List<String> = listOf("cardio", "local_fatigue", "impact", "skill", "recovery_cost", "interference", "steady_state", "intervals", "measurable")
    }
    object PAT_001 {
        const val lifting_patterns_min: Int = 1
        const val main_patterns_min: Int = 2
        const val carry_min: Int = 1
        const val core_categories_min: Int = 1
        const val rotation_per_weeks: Int = 2
    }
    object PAT_002 {
        const val min: Double = 1.0
        const val max: Double = 1.5
    }
    object PAT_003 {
        const val min: Double = 0.67
        const val max: Double = 1.5
    }
    object PAT_004 {
        const val min: Int = 1
        const val min_when_4plus_days: Int = 2
    }
    object BW_001 {
        val order: List<String> = listOf("reps", "range_of_motion", "tempo_or_pause", "leverage", "unilateral_or_less_assistance", "added_load")
    }
    object BW_002 {
        object top_of_range {
            const val push_up: Int = 15
            val pull_up: List<Int> = listOf(10, 12)
            const val squat: Int = 20
        }
        const val consecutive_sessions: Int = 2
        const val min_rir: Int = 1
        object assisted_pullup {
            const val sets: Int = 3
            const val reps: Int = 8
            const val rir: Int = 2
        }
    }
    object CORE_001 {
        const val default_spinal_flexion_sets: Int = 0
    }
    object CORE_002 {
        val hold_seconds: List<Int> = listOf(30, 45)
        val reps_per_side: List<Int> = listOf(10, 12)
        const val sessions: Int = 2
    }
    object CORE_003 {
        val sessions: List<Int> = listOf(2, 4)
        val weekly_sets: List<Int> = listOf(6, 12)
        const val max_sets_per_session: Int = 4
    }
    object MOB_001 {
        val minutes: List<Int> = listOf(3, 5)
    }
    object MOB_002 {
        const val pre_max_seconds_per_muscle: Int = 30
        val post_seconds_per_muscle: List<Int> = listOf(30, 60)
        val breathing_minutes: List<Int> = listOf(1, 2)
    }
    object MOB_003 {
    }
    object MOB_004 {
    }
    object MOB_005 {
        val minutes: List<Int> = listOf(10, 20)
        val per_week: List<Int> = listOf(2, 3)
    }
    object WU_001 {
        val raise_min: List<Int> = listOf(3, 5)
        val activate_mobilise_min: List<Int> = listOf(3, 4)
        val total_min: List<Int> = listOf(8, 12)
        val hiit_builds_cr10: List<Int> = listOf(5, 7, 8)
    }
    object WU_002 {
        val first_lift: List<Any?> = listOf(listOf("bar", listOf(8, 10)), listOf(0.5, 5.0), listOf(0.7, 3.0), listOf(0.85, listOf(1, 2)))
        object heavy_step_condition {
            const val reps_lte: Int = 6
            const val or_pct_e1rm_gte: Int = 80
        }
        const val light_threshold_kg_over_bar: Int = 10
        val light_single_set: List<Double> = listOf(0.5, 8.0)
        val second_lift: List<Any?> = listOf(listOf(0.6, 5.0), listOf(0.8, listOf(2, 3)))
    }
    object WU_003 {
        const val floor_minutes: Int = 5
    }
    object WU_004 {
        val age_50_extra_min: List<Int> = listOf(2, 3)
        const val age_65_balance_drill: Boolean = true
    }
    object RDY_001 {
        object weights {
            const val sleep_quality: Double = 0.3
            const val energy: Double = 0.3
            const val soreness: Double = 0.25
            const val stress: Double = 0.15
        }
        val scale: List<Int> = listOf(1, 5)
        const val multiplier: Int = 25
        const val max_seconds: Int = 15
    }
    object RDY_002 {
        const val min_checkins: Int = 14
        const val window_days: Int = 28
        const val min_sd: Int = 8
        const val z_clamp: Int = 2
        const val pers_center: Int = 50
        const val pers_scale: Int = 15
        const val raw_weight: Double = 0.6
        const val pers_weight: Double = 0.4
        const val raw_floor_for_light_cap: Int = 15
    }
    object RDY_003 {
        const val FULL_min: Int = 40
        const val MODIFIED_min: Int = 28
        const val LIGHT_min: Int = 15
        const val item_of_1_cap: String = "MODIFIED"
    }
    object RDY_004 {
        object MODIFIED {
            const val sets_reduction_pct: Int = 30
            const val rir_offset: Int = 1
            const val max_main_load_pct: Int = 95
            val hiit_replacement_minutes: List<Int> = listOf(15, 20)
        }
        object LIGHT {
            const val sets_reduction_pct: Int = 50
            const val max_main_load_pct: Int = 85
            const val min_rir: Int = 3
            val z1_minutes: List<Int> = listOf(10, 20)
            val mobility_minutes: List<Int> = listOf(5, 10)
        }
        object RECOVERY {
            const val resistance: Boolean = false
            val optional_z1_minutes: List<Int> = listOf(10, 30)
        }
    }
    object RDY_005 {
        const val light_cap_below_h: Int = 4
        const val modified_cap_below_h: Int = 5
    }
    object RDY_006 {
        const val min_signals: Int = 2
        const val floor: String = "LIGHT"
    }
    object RDY_007 {
        const val max_steps_up: Int = 1
    }
    object LOAD_001 {
        const val pause_exclusion_min: Int = 10
    }
    object LOAD_002 {
        const val min_minutes_after: Int = 10
        const val late_prompt_hours: Int = 24
    }
    object LOAD_003 {
        const val monotony_flag: Double = 2.0
        const val sd: String = "sample"
    }
    object LOAD_004 {
        const val acute_lambda: Double = 0.25
        const val chronic_lambda: Double = 0.0689655
        const val min_days: Int = 28
        const val flag_gt: Double = 1.5
    }
    object LOAD_005 {
        const val multiplier: Double = 1.2
        const val early_week_over_week_pct: Int = 20
        const val history_weeks: Int = 3
    }
    object LOAD_006 {
        const val phase1_days: Int = 14
        const val phase2_days: Int = 28
    }
    object DEL_001 {
        object F1 {
            const val min_lifts: Int = 2
            const val drop_pct: Int = 3
            const val consecutive_exposures: Int = 2
        }
        object F2 {
            const val rpe_over_plan: Double = 1.5
            val of_last: List<Int> = listOf(3, 4)
        }
        object F3 {
            const val sd_below: Int = 1
            const val raw_mean_below: Int = 35
        }
        object F4 {
            const val soreness_lte: Int = 2
            val of_last: List<Int> = listOf(3, 5)
            const val same_ache_days: Int = 7
        }
        object F5 {
            const val ewma_gt: Double = 1.5
            const val monotony_gt: Double = 2.0
        }
        object F6 {
            const val times: Int = 2
            const val days: Int = 7
        }
    }
    object DEL_002 {
        const val deload_now_signals: Int = 3
        const val lighter_week_signals: Int = 2
        const val lighter_week_sessions: Int = 3
        const val block_end_signals: Int = 1
        const val offer_after_weeks: Int = 10
    }
    object DEL_003 {
        val days: List<Int> = listOf(5, 7)
        const val sets_reduction_pct: Int = 50
        val load_pct: List<Int> = listOf(85, 90)
        const val min_rir: Int = 3
        const val hiit: Boolean = false
    }
    object DEL_004 {
        val load_pct: List<Int> = listOf(95, 100)
        const val week1_rir_offset: Int = 1
    }
    object PER_001 {
    }
    object PER_002 {
        const val min_weeks: Int = 4
        const val max_weeks: Int = 6
        const val default_weeks: Int = 5
    }
    object PER_003 {
        val sequence: List<String> = listOf("calibrate", "foundation", "build", "strength", "conditioning", "build_2", "strength_2", "power_athleticism", "consolidation", "review")
        const val calibrate_weeks: Int = 2
        const val flex_weeks: Int = 2
    }
    object PER_004 {
        const val aerobic_check_minutes: Int = 10
        const val aerobic_check_cr10: Int = 5
    }
    object PER_005 {
        const val pause_below_session_share: Double = 0.5
        const val restart_block_after_weeks: Int = 4
    }
    object PER_006 {
        const val top_priority_weeks: Int = 1
        const val low_priority_weeks: Int = -1
        const val min_block_weeks: Int = 4
        const val top_priority_extra_sets: Int = 2
    }
    object PROG_001 {
        const val min_step_pct: Double = 2.5
        const val max_step_pct: Double = 5.0
        const val rpe_tolerance: Double = 0.5
    }
    object PROG_002 {
        const val range_extension_max: Int = 3
        const val compound_max_reps: Int = 15
        const val isolation_max_reps: Int = 20
    }
    object PROG_003 {
        const val over_target_tolerance_pct: Int = 2
    }
    object PROG_004 {
        val hold_band: List<Double> = listOf(1.0, 1.5)
        const val reduce_pct: Int = 5
        const val second_reduce_pct: Int = 10
    }
    object PROG_005 {
    }
    object PROG_006 {
        val steady_minutes: List<Int> = listOf(2, 5)
        const val weekly_pct_max: Int = 15
        val pace_pct: List<Int> = listOf(1, 2)
        val sled_load_pct: List<Int> = listOf(5, 10)
    }
    object PROG_007 {
        object intensity_pct_week {
            const val beginner: Double = 7.5
            const val other: Int = 5
        }
        const val sets_per_week: Int = 2
        const val aerobic_pct_week: Int = 15
        const val hiit_work_min_week: Int = 2
    }
    object PROG_008 {
        val options: List<String> = listOf("yes", "unsure", "no")
        const val regress_after_no: Int = 2
    }
    object REG_001 {
        const val failures: Int = 3
        const val window_weeks: Int = 3
        const val reduce_pct: Int = 10
    }
    object REG_002 {
    }
    object REG_003 {
        const val loads_pct: Int = 95
        const val tier: String = "MODIFIED"
        val days: List<Int> = listOf(7, 13)
    }
    object REG_004 {
        val bands: List<Any?> = listOf(mapOf("days" to listOf(14, 27), "weeks" to listOf(mapOf("load" to 90, "sets" to 70), mapOf("load" to 95, "sets" to 85)), "hiit_pause_weeks" to 1), mapOf("days" to listOf(28, 55), "week1" to mapOf("load" to 80, "sets" to 60), "weekly_step" to mapOf("load" to 5, "sets" to 15), "hiit_pause_weeks" to 2), mapOf("days" to listOf(56, null), "action" to "recalibrate_and_restart_block"))
        const val older_or_flagged_shift: Int = 1
    }
    object REG_005 {
        val symptom_free_hours: List<Int> = listOf(24, 48)
        const val hiit_after_normal_sessions: Int = 2
    }
    object CAL_001 {
        val rir_5plus_increase_pct: List<Int> = listOf(20, 30)
        val rir_4_increase_pct: List<Int> = listOf(10, 15)
        const val stop_rir_lte: Int = 2
        const val stop_reduction_pct: Int = 5
        const val max_ramp_sets: Int = 5
        const val max_rpe: Int = 8
        const val known_weights_start_pct: Int = 90
        val sessions: List<Int> = listOf(1, 4)
    }
    object SUB_001 {
        const val skill_margin: Int = 1
    }
    object SUB_002 {
        object weights {
            const val pattern: Double = 0.3
            const val objective: Double = 0.2
            const val muscle: Double = 0.15
            const val equipment: Double = 0.1
            const val joint: Double = 0.1
            const val difficulty: Double = 0.07
            const val fatigue: Double = 0.05
            const val preference: Double = 0.03
        }
        object pattern_scores {
            const val same: Double = 1.0
            const val adjacent: Double = 0.5
            const val other: Double = 0.0
        }
        const val min_pattern_for_auto: Double = 0.5
    }
    object SUB_003 {
        const val step: Double = 0.05
        val bounds: List<Int> = listOf(0, 1)
    }
    object TIME_001 {
        const val cooldown_min_minutes: Int = 2
    }
    object TIME_002 {
        val steps: List<String> = listOf("rest_P4_P5_to_min", "supersets", "P5_reduce_then_drop", "P4_reduce_then_drop", "warmup_to_floor", "P3_minus_one_set", "P2_shorten_max_40pct", "P1_to_two_sets")
        const val express_below_minutes: Int = 20
        const val p2_max_cut_pct: Int = 40
    }
    object TIME_003 {
        val order: List<String> = listOf("P4_sets", "z1_minutes", "core_mobility", "skill_power")
    }
    object TIME_004 {
        const val tempo_s_per_rep: Double = 3.5
        const val per_set_overhead_s: Int = 10
        val station_change_s: List<Int> = listOf(60, 90)
        const val buffer_pct: Int = 5
        val personal_factor_bounds: List<Double> = listOf(0.8, 1.3)
    }
    object GEN_001 {
        const val steps: Int = 10
        const val deterministic: Boolean = true
        const val tie_break: String = "exercise_id"
    }
    object SCH_001 {
        val _2: List<String> = listOf("FB_A", "FB_B")
        val _3: List<String> = listOf("FB_A", "FB_B", "FB_C")
        val _4: List<String> = listOf("UPPER_H", "LOWER_H", "UPPER_M", "LOWER_M")
        val _5: List<String> = listOf("UPPER", "LOWER", "COND_CORE", "UPPER", "LOWER")
        val _6: List<String> = listOf("UPPER", "LOWER", "COND", "UPPER", "LOWER", "EASY_AEROBIC_MOBILITY")
    }
    object SCH_002 {
        const val heavy_lower_min_h: Int = 48
        const val advanced_pref_h: Int = 72
        const val max_consecutive_hard_days: Int = 3
    }
    object SCH_003 {
    }
    object EXP_001 {
        const val beginner_months_lt: Int = 12
        val intermediate_months: List<Int> = listOf(12, 36)
        const val advanced_months_gt: Int = 36
        val key_lifts: List<String> = listOf("squat", "hinge", "press", "row")
        const val lock_up_weeks: Int = 4
    }
    object EXP_002 {
        const val stall_weeks: Int = 3
        const val adherence_min: Double = 0.8
        const val beginner_max_months: Int = 9
        const val advanced_min_months: Int = 24
        const val progress_pct_week_lt: Double = 0.5
        const val window_weeks: Int = 12
        const val break_weeks: Int = 8
        const val demotion_weeks: Int = 4
    }
    object AGE_001 {
        object age_50 {
            const val hiit_max: Int = 2
            const val deload_signals: Int = 2
            const val power_year_round: Boolean = true
        }
        object age_60 {
            const val return_band_shift: Int = 1
        }
        object age_65 {
            const val balance_days: Int = 3
            const val progression_cap_multiplier: Double = 0.8
        }
    }
    object IND_001 {
        const val injury_conservative_weeks: Int = 4
    }
    object EQ_001 {
    }
    object EQ_002 {
        const val max_simultaneous_stations: Int = 2
    }
    object ADH_001 {
        const val freeze_per_weeks: Int = 4
    }
    object ADH_002 {
        val session_milestones: List<Int> = listOf(10, 25, 50, 100)
    }
    object ADH_003 {
    }
    object ADH_004 {
        val express_minutes: List<Int> = listOf(20, 30)
        const val habit_median_days: Int = 66
    }
    object DATA_001 {
        val required: List<String> = listOf("age", "experience", "days", "session_length", "equipment_inventory", "screening", "priorities", "logged_sets", "session_rpe_duration", "readiness", "pain_reports")
        val optional: List<String> = listOf("sleep_hours", "bodyweight", "body_measurements", "heart_rate", "sex", "exercise_preferences")
        val never: List<String> = listOf("location", "contacts", "photos_camera", "microphone", "advertising_id", "social_profiles", "third_party_steps_v1", "calorie_intake", "vanity_metrics")
    }
}
