"""Health-condition table v1.0 (CR-001, D-058, rule SAF-010). Approved by the Product Owner on 2026-10-09.
Run: python3 -I tools/build_health_conditions.py rules/health_conditions_v1.0.json

Zone mapping to the app's AER-001 zones: Z1 = easy/moderate (talk in full sentences),
Z2 = tempo (counts as vigorous), Z3 = intervals. Guidance that says "moderate only" maps to Z1.
"""
import json, sys

def entry(id, name, group, clearance, max_zone, hiit, impact, confidence, sources, min_rir=None, **kw):
    e = {"id": id, "name": name, "group": group, "clearance": clearance, "max_zone": max_zone, "hiit": hiit,
         "failure_allowed": False, "impact": impact}
    if min_rir is not None:
        e["min_rir"] = min_rir  # absent = app default
    e.update(kw)
    e["confidence"] = confidence
    e["sources"] = sources
    return e

STOP_UNIVERSAL = "Universal red flags (SAF-002) always apply."
E = [
 entry("hbp_controlled", "High blood pressure — a doctor or nurse has told you it is under control", "heart_and_circulation",
   clearance="none", max_zone="Z3", hiit="after_base", min_rir=2, impact="as_tolerated",
   hiit_base_weeks=4, avoid_tags=["breath_hold_max"], extra_warmup_min=0, extra_cooldown_min=5,
   prompts=["Breathe steadily: out as you lift, in as you lower. Don't hold your breath.",
            "Finish with an easy cool-down and stand up slowly."],
   stop_signs=["Sudden severe headache", "Blurred or changed vision", "Confusion, or weakness on one side (emergency)"],
   confidence="Moderate Evidence (exercise lowers BP: High; caps: Expert Practice)", sources=["PES19", "ESC20", "AAESS09", "AHA24RT", "EDW23"]),
 entry("hbp_not_controlled", "High blood pressure — not under control, newly found, or not sure", "heart_and_circulation",
   clearance="before_vigorous", clearance_prompt_now=True, max_zone="Z3", hiit="after_base", hiit_needs_scope="intervals", hiit_base_weeks=4, min_rir=3,
   impact="low", avoid_tags=["breath_hold_max", "isometric_heavy"], extra_warmup_min=5, extra_cooldown_min=5,
   prompts=["Because your blood pressure may not be under control yet, sessions stay at an easy-to-moderate effort. Check with your doctor before harder sessions.",
            "Breathe steadily and don't hold your breath."],
   stop_signs=["Sudden severe headache", "Blurred or changed vision", "Confusion, or weakness on one side (emergency)"],
   confidence="Moderate Evidence / Expert Practice", sources=["AAESS09", "ESC20", "AHA13", "EDW24"]),
 entry("t2d", "Type 2 diabetes", "metabolic",
   clearance="before_vigorous", max_zone="Z3", hiit="after_base", hiit_needs_scope="intervals", hiit_base_weeks=6, min_rir=2, impact="as_tolerated",
   scheduling={"max_consecutive_inactive_days": 2, "strength_on_consecutive_days": False}, extra_warmup_min=5,
   asks=["Do you take a diabetes medicine that can cause low blood sugar?"],
   prompts=["Short walks after meals and breaking up long sitting help.",
            "If you take a diabetes medicine that can cause low blood sugar: carry a fast-acting sugar snack when you train and know the signs of a low (shaky, sweaty, confused, unusually hungry). Lows can happen during or hours after exercise. Your diabetes care team can tell you how to plan around training.",
            "Drink water before, during and after, and avoid the hottest part of the day.",
            "If you feel unwell, or your diabetes plan says not to exercise right now, skip today."],
   stop_signs=["Shaky, sweaty, confused, blurred vision or sudden weakness: stop and follow your low-sugar plan",
               "Unusual thirst, nausea, vomiting or tummy pain: stop and get advice", "Chest discomfort or unusual breathlessness"],
   not_encoded=["glucose or ketone thresholds", "carbohydrate or medicine amounts"],
   confidence="High Evidence (training) / Moderate Evidence (safety prompts)", sources=["KAN22", "Riebe2015", "ESC20"]),
 entry("diabetes_eye", "Diabetes (type 1 or 2) with eye disease (retinopathy)", "metabolic", parent="any_diabetes",
   clearance="always", clearance_prompt_now=True, block_if=["Eye disease is unstable, or recently treated with laser or surgery"],
   max_zone="Z1", hiit="no", min_rir=3, impact="none",
   avoid_tags=["breath_hold_max", "head_down", "jumping", "overhead_heavy"], extra_warmup_min=5,
   prompts=["Ask your eye doctor what kind of exercise is safe for you."],
   stop_signs=["Sudden floaters, flashes, a 'curtain' or loss of vision: stop and get urgent eye care"],
   confidence="Moderate Evidence / Expert Practice", sources=["KAN22"]),
 entry("diabetes_feet", "Diabetes (type 1 or 2) with numbness or nerve damage in the feet", "metabolic", parent="any_diabetes",
   clearance="none", max_zone="Z3", hiit="after_base", hiit_base_weeks=4, hiit_modalities=["rower", "stationary_bike"], min_rir=2, impact="none",
   avoid_tags=["jumping", "uneven_surface_running", "high_fall_risk"], joint_limits={"ANKLE": 2}, extra_warmup_min=5,
   prompts=["Check your feet every day, wear well-fitting shoes and dry socks.", "No swimming or water workouts with an open sore on your foot."],
   stop_signs=["A new blister, wound or redness on the foot: pause standing work and get it checked"],
   confidence="Moderate Evidence / Expert Practice", sources=["KAN22"]),
 entry("diabetes_autonomic", "Diabetes (type 1 or 2) affecting heart rate or blood pressure (autonomic neuropathy)", "metabolic", parent="any_diabetes",
   clearance="always", clearance_prompt_now=True, max_zone="Z1", hiit="no", min_rir=3, impact="low", effort_by="feel_only",
   extra_warmup_min=10, extra_cooldown_min=10, prompts=["Change position slowly.", "Take extra care in heat and drink water."],
   stop_signs=["Dizziness or light-headedness"], confidence="Moderate Evidence / Expert Practice", sources=["KAN22"]),
 entry("t1d", "Type 1 diabetes", "metabolic",
   clearance="before_vigorous", max_zone="Z3", hiit="after_base", hiit_needs_scope="intervals", hiit_base_weeks=4, min_rir=2, impact="as_tolerated",
   default_order="strength_then_cardio", extra_warmup_min=5,
   prompts=["Check your glucose before, during and after training as your care plan advises.", "Carry fast-acting sugar.",
            "Lows can happen up to a day later, especially overnight after afternoon or evening sessions.", "Avoid training alone in risky settings."],
   stop_signs=["Signs of a low: stop and follow your care plan", "Feeling unwell with nausea or vomiting: stop and follow your care plan"],
   not_encoded=["glucose bands", "carbohydrate grams", "medicine dose changes", "a 'severe low in the last 24 h' gate (regulatory review first)"],
   confidence="Moderate Evidence (consensus)", sources=["RID17", "Riebe2015"]),
 entry("heart", "Heart condition (coronary disease, after a heart attack or stent, heart failure, irregular heartbeat)", "heart_and_circulation",
   clearance="always", clearance_prompt_now=True, max_zone="Z1", hiit="no", min_rir=3, impact="low",
   after_clearance={"light_moderate": {"max_zone": "Z1", "min_rir": 2}, "vigorous": {"max_zone": "Z2", "min_rir": 2}, "intervals": {"max_zone": "Z3", "hiit": "after_base"}},
   avoid_tags=["breath_hold_max", "isometric_heavy"], extra_warmup_min=10, extra_cooldown_min=10, effort_by="feel_preferred",
   sub_flags={"heart_failure": "only if your doctor says it is stable",
              "pacemaker_icd": "check with your doctor before upper-body weights",
              "recent_breastbone_surgery": "no loaded overhead work and no heavy pushing or pulling until your surgical team clears it",
              "aortic_or_connective_tissue_or_cardiomyopathy": "always avoid breath_hold_max and isometric_heavy unless cleared"},
   # 1.0.1 (review R3-01): the breastbone sub-flag's meaning as controls. "No heavy pushing or pulling" is encoded strictly:
   # nothing that loads the arms, shoulders or chest, and no arm-driven cardio machines, until the surgical team clears it.
   sub_flag_effects={"recent_breastbone_surgery": {
       "avoid_tags": ["overhead", "overhead_heavy", "upper_body_loaded", "breath_hold_max", "isometric_heavy"],
       "avoid_modalities": ["rower", "skierg", "air_fan_bike", "sled", "battle_ropes", "kettlebell", "carries", "medball"]}},
   prompts=["We start gently until your doctor or cardiac rehab team says you can do more.",
            "Go by how hard it feels rather than heart-rate numbers if your heartbeat is irregular or a medicine slows it."],
   stop_signs=["Chest pain, pressure or tightness", "Unusual breathlessness", "Dizziness or light-headedness", "Palpitations or a racing or irregular heartbeat",
               "Unusual tiredness — stop; if it doesn't settle within a few minutes, call emergency services; don't train again until cleared"],
   confidence="Moderate Evidence (benefit of rehab: High) / Expert Practice (caps)", sources=["Riebe2015", "ESC20", "AHA24RT", "CCD23", "EDW24"]),
 entry("asthma", "Asthma", "breathing",
   clearance="none", ask_control_status=True, max_zone="Z3", hiit="yes", impact="as_tolerated",
   if_not_controlled={"max_zone": "Z1", "hiit": "no", "prompt": "Get your asthma reviewed before hard training."},
   extra_warmup_min=10, warmup_style="intervals",
   prompts=["Follow your asthma action plan for exercise and keep with you what it says to carry.", "Cool down gradually.",
            "In cold, dry air cover your mouth and nose or train indoors. On high-pollen or poor-air days, train indoors."],
   stop_signs=["Wheeze, chest tightness or cough that doesn't settle with rest and your usual plan", "Can't speak in full sentences", "Blue or grey lips (emergency)"],
   confidence="Moderate Evidence", sources=["ATS13", "AAAAI22"]),
 entry("oa_knee", "Knee osteoarthritis (arthritis)", "joints",
   clearance="none", max_zone="Z3", hiit="after_base", hiit_low_impact_only=True, min_rir=2, impact="low",
   impact_unlock={"after_weeks": 4, "if": "pain rule met", "opt_in": True},
   joint_limits={"KNEE": 2}, joint_limit_unlock={"KNEE": 3, "after_weeks_meeting_pain_rule": 2},
   avoid_tags_at_start=["jumping"], range_limited_tags=["deep_knee_flexion"], extra_warmup_min=5,
   pain_rule={"during_max_0_10": 5, "next_morning": "back to usual", "else": "reduce load or range for that joint"},
   prompts=["Some extra joint discomfort when you start exercising is common and usually settles as you get stronger.",
            "Regular strengthening and cardio are among the most recommended things for people with joint arthritis."],
   stop_signs=["A hot, very swollen joint", "The joint locking or giving way", "Sudden severe pain", "Pain still worse than usual the next day (reduce load; if it keeps happening, see a health professional)"],
   confidence="High Evidence (exercise) / Expert Practice (limits and pain rule)", sources=["OARSI19", "ACR20", "NG226", "GLAD12"]),
 entry("oa_hip", "Hip osteoarthritis (arthritis)", "joints",
   clearance="none", max_zone="Z3", hiit="after_base", hiit_low_impact_only=True, min_rir=2, impact="low",
   impact_unlock={"after_weeks": 4, "if": "pain rule met", "opt_in": True},
   joint_limits={"HIP": 2}, joint_limit_unlock={"HIP": 3, "after_weeks_meeting_pain_rule": 2},
   avoid_tags_at_start=["jumping"], range_limited_tags=["deep_hip_flexion"], extra_warmup_min=5,
   pain_rule={"during_max_0_10": 5, "next_morning": "back to usual", "else": "reduce load or range for that joint"},
   prompts=["Some extra joint discomfort when you start exercising is common and usually settles as you get stronger."],
   stop_signs=["A hot, very swollen joint", "The joint locking or giving way", "Sudden severe pain", "Pain still worse than usual the next day"],
   confidence="High Evidence (exercise) / Expert Practice (limits and pain rule)", sources=["OARSI19", "ACR20", "NG226", "GLAD12"]),
 entry("low_back_pain", "Low back pain", "joints",
   clearance="none", max_zone="Z3", hiit="as_tolerated", min_rir=2, min_rir_applies_to_tags=["spinal_loading"], impact="as_tolerated",
   flare_mode={"switch": "user taps 'my back is flaring'", "joint_limits": {"SPINE": 2}, "avoid_tags": ["spinal_loading", "spinal_flexion"],
               "keep": ["walking", "cycling_if_allowed", "gentle_mobility"], "exit_after_sessions_without_next_day_flare": 3},
   extra_warmup_min=5, never_recommend=["back belts or braces for back pain"],
   prompts=["Keeping active helps back pain recover; long rest in bed usually doesn't.", "Pick exercise you enjoy and can do regularly.",
            "Mild discomfort is OK; ease off any move that makes the pain sharply worse."],
   stop_signs=["Emergency: numbness or tingling around the genitals or bottom; new trouble peeing or loss of bowel control; weakness or numbness in both legs; chest pain; back pain after a serious accident",
               "See a doctor soon: pain worse at night or not easing with rest; unexplained weight loss; feeling feverish or unwell; pain between the shoulder blades; not improving after a few weeks"],
   confidence="Moderate Evidence (stay active) / Expert Practice (flare limits)", sources=["NG59", "WHO23", "NHSBP"]),
 entry("osteoporosis", "Osteoporosis or osteopenia (no spine fracture)", "bones",
   clearance="suggest", max_zone="Z3", hiit="yes", min_rir=1, impact="encouraged",
   impact_dose={"block": "bone-loading block (≤5 min of low-level landings, e.g. heel drops, small hops)", "impacts_per_session_min": 50, "sessions": "most days", "unless": "osteoarthritis or frailty limits", "con004": "a bone-loading block is not a CON-004 impact session (CON-004 1.1.0)"},
   avoid_tags=["spinal_flexion", "loaded_spinal_rotation"], required_work={"balance_per_week": 2, "back_extensor_per_week": 2}, extra_warmup_min=5,
   prompts=["Bend from the hips with a straight back when lifting.", "Strength, impact and balance exercise are recommended for bone health.",
            "If you've had a fracture, check with your doctor or physio before starting."],
   stop_signs=["Sudden sharp back pain during or after a lift or bend: stop and get it checked"],
   confidence="Moderate Evidence", sources=["ROS22", "ESSA17", "IOF"]),
 entry("osteoporosis_spine_fracture", "Osteoporosis with a spine fracture or more than one low-impact fracture", "bones", parent="osteoporosis",
   clearance="always", clearance_prompt_now=True, clearance_text="A physiotherapist's input at the start is strongly suggested.",
   max_zone="Z2", hiit="no", min_rir=3, impact="none", impact_max="brisk walking",
   avoid_tags=["jumping", "spinal_flexion", "loaded_spinal_rotation", "high_fall_risk"], joint_limits={"SPINE": 2}, extra_warmup_min=5,
   prompts=["Brisk walking is your impact work for now."], stop_signs=["Sudden sharp back pain: stop and get it checked"],
   confidence="Moderate Evidence / Expert Practice", sources=["ROS22", "ESSA17", "IOF"]),
 entry("pregnancy", "Pregnant", "pregnancy",
   clearance="always", block_if=["If your pregnancy care provider has told you any of these apply: waters broken; premature labour; unexplained ongoing vaginal bleeding; placenta praevia after 28 weeks; pre-eclampsia; weak cervix; baby not growing as expected; triplets or more; uncontrolled type 1 diabetes, high blood pressure or thyroid disease; another serious heart, lung or whole-body condition — follow your provider's advice instead of a training plan"],
   attest_if=["If your provider has told you any of these apply: repeated pregnancy loss; high blood pressure in this pregnancy; an earlier premature birth; mild or moderate heart or lung disease; anaemia with symptoms; under-nutrition or an eating disorder; twins after 28 weeks — 'my provider has OK'd exercise'"],
   max_zone="Z1", max_zone_if_previously_vigorous_and_ok="Z2", hiit="no", min_rir=3, impact="only_if_already_doing_it",
   avoid_tags=["breath_hold_max", "high_fall_risk", "contact", "olympic_lift"], avoid_tags_from_week={"20": ["supine_lying", "prone_lying"]},
   avoid_supine_any_time_if="dizzy or unwell lying on the back", goal_effects="fat-loss goal not offered; no weight-loss expectations, weight trend or rate check-in (FL-001)", extra_warmup_min=5,
   environment=["No hot or humid rooms (including hot yoga); drink water", "Altitude above 2,500 m and scuba diving: informational note"],
   prompts=["Talk with your pregnancy care provider about your exercise plan.", "Aim for regular moderate activity most days.",
            "Pelvic floor exercises can be done daily; a pelvic health physio can teach the technique.", "If you feel dizzy or unwell lying on your back, switch position."],
   stop_signs=["Breathlessness that doesn't settle with rest", "Severe chest pain", "Regular painful contractions", "Vaginal bleeding", "Ongoing fluid leakage", "Dizziness or faintness that doesn't settle with rest — stop and contact your provider or maternity unit"],
   confidence="High Evidence (activity is safe) / Expert Practice (caps)", sources=["CAN19", "ACOG20"]),
 entry("postpartum", "Had a baby in the last 12 months", "pregnancy",
   clearance="suggest", phases=[
     {"weeks": [0, 6], "until": "healed and bleeding not increasing with activity", "max_zone": "Z1", "hiit": "no", "min_rir": 4, "impact": "none", "focus": ["walking", "daily pelvic floor exercises"]},
     {"weeks": [6, 12], "attest": "healed; no pelvic floor symptoms", "max_zone": "Z1", "hiit": "no", "min_rir": 3, "impact": "none", "focus": ["low-impact cardio", "progressive strength", "core work without doming"]},
     {"weeks": [12, 52], "impact_unlock": "user records passing the return-to-impact checks", "max_zone": "Z3", "hiit": "after_impact_unlocked", "min_rir": 2, "impact": "progressive"}],
   impact_checks=["Walk 30 min", "Balance on one leg 10 s", "Single-leg squat ×10 each side", "Jog on the spot 1 min", "Forward bounds ×10", "Hop on the spot ×10 each leg", "Single-leg 'running man' ×10 each side — all without pain, heaviness, dragging or leaking"],
   max_zone="by_phase", hiit="by_phase", min_rir="by_phase", impact="by_phase", avoid_tags_early=["jumping", "breath_hold_max"], extra_warmup_min=5,
   goal_effects="fat-loss goal is not the default; it can be chosen after 12 weeks",
   prompts=["Daily pelvic floor exercises help.", "If you notice leaking, heaviness or dragging, or a bulge or dome along your tummy during exercise, ease off that move and consider a pelvic health physio.",
            "If breastfeeding, feed or express before training."],
   stop_signs=["Heavy or increasing bleeding", "Severe tummy pain", "Worsening caesarean wound pain", "Calf pain or swelling", "Chest pain", "Dizziness", "Breathlessness at rest — stop and get care"],
   confidence="Moderate Evidence (activity, pelvic floor) / Expert Practice (timeline)", sources=["CAN25", "GOOM19"]),
 entry("obesity", "Living with obesity (told by a doctor; BMI 30+, or 27.5+ for South Asian people)", "body_weight",
   clearance="none", max_zone="Z3", hiit="after_base", hiit_base_weeks=4, hiit_low_impact_only=True, min_rir=2, impact="low_volume",
   joint_limits={"KNEE": 3}, extra_warmup_min=5,
   prompts=["Build up gradually; fitness gains count even when the scale doesn't move.", "Take care in heat and drink water.", "Supportive shoes and low-impact cardio are easier on the joints."],
   stop_signs=["Signs of heat illness (dizziness, nausea, headache, confusion): stop, cool down and drink water"],
   confidence="Moderate Evidence / Expert Practice (caps)", sources=["Donnelly2009", "Oppert2021", "WHO04", "Misra2025", "Riebe2015"]),
 entry("obesity_severe", "Living with severe obesity (BMI 35+, or 32.5+ for South Asian people)", "body_weight", parent="obesity",
   clearance="suggest", max_zone="Z1", max_zone_after_weeks={"weeks": 8, "zone": "Z3"}, hiit="after_base", hiit_base_weeks=8, hiit_modalities=["rower", "stationary_bike"],
   min_rir=2, impact="none_at_start", impact_unlock={"after_weeks": 8, "opt_in": True}, joint_limits={"KNEE": 2}, joint_limit_unlock={"KNEE": 3, "after_weeks": 8},
   positions_note="Offer alternatives to getting up and down from the floor and to long lying on the back if uncomfortable", extra_warmup_min=5,
   avoid_supine_any_time_if="uncomfortable lying on the back",
   prompts=["Build up gradually; fitness gains count even when the scale doesn't move."],
   stop_signs=["Signs of heat illness: stop, cool down and drink water"],
   confidence="Expert Practice", sources=["Misra2025", "WHO04", "Oppert2021"]),
 entry("stroke", "Had a stroke", "other", optional=True,
   clearance="always", clearance_prompt_now=True, max_zone="Z1", max_zone_after_clearance="Z2", hiit="no", min_rir=3, impact="low",
   avoid_tags=["high_fall_risk", "unsupported_single_leg"], extra_warmup_min=10, extra_cooldown_min=10,
   prompts=["Use handrails or seated options when balance is a concern."],
   stop_signs=["New face droop, arm weakness or speech difficulty: call emergency services"],
   confidence="Moderate Evidence (AHA statement) / Expert Practice (caps)", sources=["AHA14ST"]),
 entry("copd", "COPD (long-term lung disease)", "breathing", optional=True,
   clearance="always", clearance_prompt_now=True, clearance_text="Ask about pulmonary rehabilitation.", max_zone="Z1", hiit="no", min_rir=3, impact="low",
   extra_warmup_min=10, prompts=["Go by your breathing: you should be able to speak a short sentence."],
   stop_signs=["Breathlessness much worse than usual or not settling", "Chest pain", "Blue lips (emergency)"],
   confidence="Limited Evidence (not fully verified)", sources=["GOLD26"]),
 entry("cancer", "Living with or after cancer", "other", optional=True,
   clearance="suggest", clearance_always_if=["in active treatment", "cancer has spread to the bones", "lymphoedema"], pending_verification=["bone-spread and lymphoedema cautions (Campbell 2019 full text not read)"],
   goal_effects_if="in active treatment: fat-loss goal not the default; no weight-loss expectations or rate check-in (FL-001)",
   max_zone="Z2", hiit="no", min_rir=2, impact="as_tolerated", impact_none_if=["cancer has spread to the bones"], extra_warmup_min=5,
   prompts=["Exercise is generally safe and helpful during and after cancer care; your care team can tell you about any limits."],
   stop_signs=[STOP_UNIVERSAL], confidence="Moderate Evidence (benefit) / details unverified", sources=["CAM19"]),
]

doc = {
  "table": "health_conditions", "version": "1.0.1", "status": "APPROVED 2026-10-09 (Research Update 1.1) for personal use; clinician and regulatory review required before any public release",
  "rule": "SAF-010",
  "changes": [
    {"version": "1.0.1", "date": "2026-10-09", "kind": "PATCH (encoding of the approved wording; no entry becomes less restrictive)",
     "items": ["parent_groups: a diabetes add-on picked without type 1 or type 2 brings both base entries (review R3-04)",
               "heart: sub_flag_effects encode 'recent breastbone surgery' as controls (review R3-01)",
               "obesity_severe: the positions note becomes 'no lying on the back' when the user says it is uncomfortable (review R3-14)"]}],
  "parent_groups": {"any_diabetes": {"members": ["t1d", "t2d"],
                    "rule": "an add-on entry picked without any member brings every member (most restrictive), until the user says which type"}},
  "unknown_ids": "an ID the table does not know (renamed entry, stale stored value) resolves to SAF-001 conservative mode with a doctor's-OK prompt; it never drops limits",
  "zone_mapping": "App zones per AER-001: Z1 easy/moderate (full sentences), Z2 tempo (vigorous), Z3 intervals. 'Moderate only' guidance maps to Z1.",
  "combine": "First resolve each entry for today (its phase, unlocks, control status and the user's clearance scope); then each control takes its most restrictive value using merge_orders. Prompts, stop signs, avoid-tags and positions are unions; joint limits take the lowest value per joint; warm-up and cool-down extras take the highest; scheduling limits take the strictest value; HIIT modality lists intersect (empty = no HIIT); impact_dose is kept only if the merged impact is 'encouraged'.",
  "merge_orders": {
    "max_zone": ["Z1", "Z2", "Z3"],
    "hiit": ["no", "after_base", "as_tolerated", "yes"],
    "hiit_base_weeks": "highest",
    "min_rir": "highest; absent = app default",
    "impact": ["none", "low", "low_volume", "only_if_already_doing_it", "as_tolerated", "encouraged"],
    "clearance": ["none", "suggest", "before_vigorous", "always"],
    "failure_allowed": "false if any entry is false"},
  "resolve_before_merge": {"none_at_start": "none until its unlock, then low", "by_phase": "the current phase's values", "if_not_controlled": "applies when the status answer is no or not sure", "after_clearance": "applies to the user's confirmed scope", "max_zone_after_weeks": "applies once the weeks have passed"},
  "clearance_definitions": {
    "none": "no doctor's OK needed; nothing locked",
    "suggest": "the app suggests a doctor's or physio's OK; nothing locked",
    "before_vigorous": "until the user confirms a doctor's OK for vigorous exercise: max zone Z1, no HIIT, min RIR 3. HIIT also needs the 'intervals' scope when hiit_needs_scope says so",
    "always": "until the user confirms a doctor's OK: SAF-001 conservative mode (Z1 only, no HIIT, min RIR 3, no failure, low impact); after it, the entry's limits apply up to the confirmed scope"},
  "status_question": "Has a doctor or nurse told you this is currently under control / stable? (yes / no / not sure; not sure counts as no)",
  "clearance_attestation": ["none", "light_moderate", "vigorous", "intervals"],
  "never": ["read or threshold clinical values (blood pressure, glucose, ketones, oxygen, ECG)", "name a medicine, dose, carbohydrate amount or value target", "diagnose or interpret symptoms", "claim to treat, manage, relieve or lower a condition"],
  "existing_library_tags_used": ["deep_knee_flexion", "overhead", "spinal_loading", "spinal_flexion", "jumping", "wrist_extension_load"],
  "new_library_tags": ["breath_hold_max", "isometric_heavy", "loaded_spinal_rotation", "deep_hip_flexion", "head_down", "supine_lying", "prone_lying", "high_fall_risk", "contact", "olympic_lift", "uneven_surface_running", "overhead_heavy", "unsupported_single_leg", "upper_body_loaded"],
  "entries": E,
}
out = sys.argv[1]
json.dump(doc, open(out, "w"), indent=1, ensure_ascii=False)
print(len(E), "entries", sum(1 for e in E if e.get("optional")), "optional")
