#!/usr/bin/env python3
"""Every engine ReasonKey has a plain-language string (COACH-001), and ReasonTexts.kt maps keys to those strings.

    python3 tools/gen_reason_texts.py          # writes app/.../ui/text/ReasonTexts.kt
    python3 tools/gen_reason_texts.py --check  # fails if a key has no string, a string has no key, or the Kotlin file is stale
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECISION = ROOT / "engine/src/main/kotlin/com/personalfitnesscoach/engine/core/Decision.kt"
XML = ROOT / "app/src/main/res/values/strings_reasons.xml"
OUT = ROOT / "app/src/main/kotlin/com/personalfitnesscoach/app/ui/text/ReasonTexts.kt"


def keys():
    s = DECISION.read_text(encoding="utf-8")
    m = re.search(r"enum class ReasonKey \{(.*?)\n\}", s, re.S)
    body = re.sub(r"//[^\n]*", "", m.group(1))
    return [k.strip() for k in body.replace("\n", " ").split(",") if k.strip()]


def names():
    return [e.get("name") for e in ET.parse(XML).getroot().findall("string")]


def render(ks):
    lines = [
        "// GENERATED by tools/gen_reason_texts.py from the engine's ReasonKey and res/values/strings_reasons.xml - do not edit by hand.",
        "package com.personalfitnesscoach.app.ui.text",
        "",
        "import com.personalfitnesscoach.R",
        "import com.personalfitnesscoach.engine.core.ReasonKey",
        "",
        "/** The plain-language line for each engine reason (COACH-001). Unknown names (an older log entry) get the generic line. */",
        "object ReasonTexts {",
        "    fun of(key: ReasonKey): Int = when (key) {",
    ]
    for k in ks:
        lines.append(f"        ReasonKey.{k} -> R.string.reason_{k.lower()}")
    lines += [
        "    }",
        "",
        "    fun of(name: String): Int = ReasonKey.entries.firstOrNull { it.name == name }?.let { of(it) } ?: R.string.reason_unknown",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    ks = keys()
    ns = set(names())
    want = {"reason_" + k.lower() for k in ks}
    missing = sorted(want - ns)
    extra = sorted(n for n in ns - want if n != "reason_unknown")
    if "reason_unknown" not in ns:
        missing.append("reason_unknown")
    text = render(ks)
    if "--check" in sys.argv:
        ok = True
        if missing:
            print("missing strings:", ", ".join(missing)); ok = False
        if extra:
            print("strings with no reason key:", ", ".join(extra)); ok = False
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run tools/gen_reason_texts.py"); ok = False
        if not ok:
            sys.exit(1)
        print(f"reason texts OK: {len(ks)} keys")
        return
    if missing or extra:
        print("missing:", missing, "extra:", extra)
        sys.exit(1)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(ks)} keys)")


if __name__ == "__main__":
    main()
