"""Generate engine/src/main/kotlin/com/personalfitnesscoach/engine/registry/GeneratedRegistry.kt
from rules/rule_registry_v1.0.json (decision D-030).

Every rule becomes a Kotlin `object` named after its ID (SAF-001 -> SAF_001) holding
its parameters as typed constants, so code that references an unknown rule or
parameter does not compile. Run after any registry change:

    python3 -I tools/gen_registry_kotlin.py          # write the file
    python3 -I tools/gen_registry_kotlin.py --check  # CI: fail if stale
"""
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "rules" / "rule_registry_v1.0.json"
OUT = ROOT / "engine/src/main/kotlin/com/personalfitnesscoach/engine/registry/GeneratedRegistry.kt"

KEYWORDS = {"as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in",
            "interface", "is", "null", "object", "package", "return", "super", "this", "throw",
            "true", "try", "typealias", "typeof", "val", "var", "when", "while"}


def ident(key: str) -> str:
    name = re.sub(r"[^0-9A-Za-z_]", "_", key)
    if not name or name[0].isdigit():
        name = "_" + name
    if name in KEYWORDS:
        name = name + "_"
    return name


def kt_scalar(v):
    if isinstance(v, bool):
        return ("Boolean", "true" if v else "false")
    if isinstance(v, int):
        return ("Int", str(v))
    if isinstance(v, float):
        return ("Double", repr(v))
    if isinstance(v, str):
        return ("String", json.dumps(v, ensure_ascii=False).replace("$", "\\$"))
    if v is None:
        return ("Nothing?", "null")
    raise TypeError(v)


def kt_list(items):
    """Typed list when homogeneous (Int lists widen to Double if mixed with floats)."""
    if all(isinstance(x, bool) for x in items) and items:
        return "List<Boolean>", "listOf(" + ", ".join(kt_scalar(x)[1] for x in items) + ")"
    if items and all(isinstance(x, int) and not isinstance(x, bool) for x in items):
        return "List<Int>", "listOf(" + ", ".join(str(x) for x in items) + ")"
    if items and all(isinstance(x, (int, float)) and not isinstance(x, bool) for x in items):
        return "List<Double>", "listOf(" + ", ".join(repr(float(x)) for x in items) + ")"
    if items and all(isinstance(x, str) for x in items):
        return "List<String>", "listOf(" + ", ".join(kt_scalar(x)[1] for x in items) + ")"
    if not items:
        return "List<Nothing>", "emptyList()"
    return "List<Any?>", "listOf(" + ", ".join(kt_any(x) for x in items) + ")"


def kt_any(v):
    if isinstance(v, list):
        return kt_list(v)[1]
    if isinstance(v, dict):
        return "mapOf(" + ", ".join(f"{json.dumps(k)} to {kt_any(x)}" for k, x in v.items()) + ")"
    return kt_scalar(v)[1]


def emit_obj(name, params, indent):
    pad = "    " * indent
    lines = [f"{pad}object {name} {{"]
    for k, v in params.items():
        n = ident(k)
        if isinstance(v, dict):
            lines += emit_obj(n, v, indent + 1)
        elif isinstance(v, list):
            t, lit = kt_list(v)
            lines.append(f"{pad}    val {n}: {t} = {lit}")
        else:
            t, lit = kt_scalar(v)
            if t == "Nothing?":
                lines.append(f"{pad}    val {n}: Any? = null")
            else:
                lines.append(f"{pad}    const val {n}: {t} = {lit}")
    lines.append(f"{pad}}}")
    return lines


def generate() -> str:
    raw = SRC.read_bytes()
    reg = json.loads(raw)
    sha = hashlib.sha256(raw).hexdigest()
    out = [
        "// GENERATED by tools/gen_registry_kotlin.py from rules/rule_registry_v1.0.json — DO NOT EDIT.",
        "// Regenerate after any registry change; CI fails if this file is stale (decision D-030).",
        "@file:Suppress(\"ObjectPropertyName\", \"ClassName\", \"unused\", \"SpellCheckingInspection\")",
        "",
        "package com.personalfitnesscoach.engine.registry",
        "",
        "object Registry {",
        f"    const val VERSION: String = \"{reg['registry_version']}\"",
        f"    const val SHA256: String = \"{sha}\"",
        f"    const val RULE_COUNT: Int = {len(reg['rules'])}",
        "",
        "    /** Every rule ID with its confidence label, for the coach's \"Why?\" detail. */",
        "    val confidence: Map<String, String> = mapOf(",
    ]
    out += [f"        \"{r['rule_id']}\" to {json.dumps(r['confidence'])}," for r in reg["rules"]]
    out += ["    )", "", "    val titles: Map<String, String> = mapOf("]
    out += [f"        \"{r['rule_id']}\" to {json.dumps(r['title'], ensure_ascii=False).replace('$', chr(92) + '$')}," for r in reg["rules"]]
    out += ["    )", "}", "", "/** Rule identifiers; use these instead of string literals. */", "object RuleIds {"]
    out += [f"    const val {ident(r['rule_id'])}: String = \"{r['rule_id']}\"" for r in reg["rules"]]
    out += ["}", "", "/** Typed parameters, one object per rule. */", "object P {"]
    for r in reg["rules"]:
        out += emit_obj(ident(r["rule_id"]), r["parameters"], 1)
    out += ["}", ""]
    return "\n".join(out)


def main():
    text = generate()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("GeneratedRegistry.kt is stale: run python3 -I tools/gen_registry_kotlin.py")
            sys.exit(1)
        print("GeneratedRegistry.kt is up to date")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
